name: image

on: 
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:


jobs: 
  build:
    name: build
    runs-on: [self-hosted, Linux, X64]
    steps:
    - uses: actions/checkout@v2
      env:
        GIT_PR_SHA: ${{github.event.pull_request.head.sha}}
        GIT_PR_SHA_SHORT: "${{ env.GIT_PR_SHA:0:10 }}"

    - name: add go path
      run: echo '~/go/bin' >> "$GITHUB_PATH"

    - name: TAG=${{ env.GIT_PR_SHA }} make local-image-build 
      run:  TAG=${{ env.GIT_PR_SHA }} make local-image-build
    
    - name: auth.json
      run: |
        [ -d ~/.docker ] || mkdir ~/.docker
        cat > ~/.docker/config.json <<'EOF'
        ${{ secrets.AUTH_JSON }}
        EOF
    
    - name: make local-image-push
      run: make local-image-push
  