name: lint

on: 
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:



jobs: 
  lint:
    name: golangci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: add go path
      run: echo '~/go/bin' >> "$GITHUB_PATH"

    - name: make lint
      run: make lint

