name: OpenShift - Tests

env:
  REGISTRY: quay.io/openshift-psap
  REGISTRY_USER: ${{ secrets.QUAY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}


  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}

on: push

jobs: 
  openshift-ci-cd:
    name: Build and deploy to OpenShift
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2

    - name: Check Local Storage
      run: | 
        sudo df -h

    - name: Local Image Build
      run: | 
        make local-image-build
    
    - name: Podman Login
      run: |
        podman login -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }}
    
    - name: Local Image push
      run: | 
        make local-image-push

    - name: Log in to OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: default

    - name: Reploy SRO
      run: | 
        make undeploy
        make deploy

    - name: Check conditions
      run: | 
        oc get clusteroperator special-resource-operator

    - name: Deploy driver-container-base
      run: | 
        make