name: unit

on: 
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:



jobs: 
  unit:
    name: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: make unit
      run: make unit

